add_executable(tinylsm_cli app/main.cpp)
target_link_libraries(tinylsm_cli PRIVATE tinylsm)
add_executable(tinylsm_bench bench/main.cpp)
target_link_libraries(tinylsm_bench PRIVATE tinylsm)
add_executable(tinylsm_rigorous bench/rigorous.cpp)
target_link_libraries(tinylsm_rigorous PRIVATE tinylsm)
target_compile_options(tinylsm_rigorous PRIVATE -Wall -Wextra)
add_executable(tinylsm_crash_acceptance tests/crash_acceptance.cpp)
target_link_libraries(tinylsm_crash_acceptance PRIVATE tinylsm)
add_test(NAME tinylsm_crash_acceptance COMMAND tinylsm_crash_acceptance)
set_tests_properties(tinylsm_crash_acceptance PROPERTIES TIMEOUT 60)
# Optional comparison benchmark: measures LevelDB with the identical workload so
# the portfolio charts plot a real head-to-head run (design section 7).
# Configure with -DTINYLSM_LEVELDB_INCLUDE_DIR=<dir> -DTINYLSM_LEVELDB_LIBRARY=<libleveldb.a>
set(TINYLSM_LEVELDB_INCLUDE_DIR "" CACHE PATH "LevelDB include directory (leveldb/db.h)")
set(TINYLSM_LEVELDB_LIBRARY "" CACHE FILEPATH "Path to libleveldb.a")
find_package(Snappy QUIET)
if(TINYLSM_LEVELDB_INCLUDE_DIR AND TINYLSM_LEVELDB_LIBRARY)
  add_executable(tinylsm_bench_leveldb bench/compare_leveldb.cpp)
  target_include_directories(tinylsm_bench_leveldb PRIVATE ${TINYLSM_LEVELDB_INCLUDE_DIR})
  target_link_libraries(tinylsm_bench_leveldb PRIVATE ${TINYLSM_LEVELDB_LIBRARY} Threads::Threads)
  if(TARGET Snappy::snappy)
    target_link_libraries(tinylsm_bench_leveldb PRIVATE Snappy::snappy)
  elseif(Snappy_FOUND)
    target_link_libraries(tinylsm_bench_leveldb PRIVATE ${SNAPPY_LIBRARIES})
  else()
    target_link_libraries(tinylsm_bench_leveldb PRIVATE snappy)
  endif()
  target_compile_options(tinylsm_bench_leveldb PRIVATE -Wall -Wextra)
  add_executable(tinylsm_rigorous_leveldb bench/rigorous_leveldb.cpp)
  target_include_directories(tinylsm_rigorous_leveldb PRIVATE ${TINYLSM_LEVELDB_INCLUDE_DIR})
  target_link_libraries(tinylsm_rigorous_leveldb PRIVATE ${TINYLSM_LEVELDB_LIBRARY} Threads::Threads)
  if(TARGET Snappy::snappy)
    target_link_libraries(tinylsm_rigorous_leveldb PRIVATE Snappy::snappy)
  elseif(Snappy_FOUND)
    target_link_libraries(tinylsm_rigorous_leveldb PRIVATE ${SNAPPY_LIBRARIES})
  else()
    target_link_libraries(tinylsm_rigorous_leveldb PRIVATE snappy)
  endif()
  target_compile_options(tinylsm_rigorous_leveldb PRIVATE -Wall -Wextra)
endif()
# Optional LMDB comparison: system library (liblmdb-dev). Same rigorous
# workload, so the third engine gets no home field either.
find_library(TINYLSM_LMDB_LIBRARY lmdb)
if(TINYLSM_LMDB_LIBRARY)
  add_executable(tinylsm_rigorous_lmdb bench/rigorous_lmdb.cpp)
  target_link_libraries(tinylsm_rigorous_lmdb PRIVATE ${TINYLSM_LMDB_LIBRARY} Threads::Threads)
  target_compile_options(tinylsm_rigorous_lmdb PRIVATE -Wall -Wextra)
endif()
# Optional SQLite comparison: amalgamation directory (sqlite3.c + sqlite3.h)
# via -DTINYLSM_SQLITE_DIR=<dir>, or a system libsqlite3. Same rigorous
# workload, so the fourth engine gets no home field either.
set(TINYLSM_SQLITE_DIR "" CACHE PATH "SQLite amalgamation directory (sqlite3.c + sqlite3.h)")
if(TINYLSM_SQLITE_DIR AND EXISTS "${TINYLSM_SQLITE_DIR}/sqlite3.c")
  add_library(tinylsm_sqlite_amalgamation "${TINYLSM_SQLITE_DIR}/sqlite3.c")
  set_target_properties(tinylsm_sqlite_amalgamation PROPERTIES LINKER_LANGUAGE C)
  target_include_directories(tinylsm_sqlite_amalgamation PUBLIC ${TINYLSM_SQLITE_DIR})
  # sqlite3.c is C; silence its warnings so -Wall -Wextra stays useful for us.
  target_compile_options(tinylsm_sqlite_amalgamation PRIVATE -w)
  add_executable(tinylsm_rigorous_sqlite bench/rigorous_sqlite.cpp)
  target_include_directories(tinylsm_rigorous_sqlite PRIVATE ${TINYLSM_SQLITE_DIR})
  target_link_libraries(tinylsm_rigorous_sqlite PRIVATE tinylsm_sqlite_amalgamation Threads::Threads ${CMAKE_DL_LIBS})
  target_compile_options(tinylsm_rigorous_sqlite PRIVATE -Wall -Wextra)
else()
  find_library(TINYLSM_SQLITE_LIBRARY sqlite3)
  find_path(TINYLSM_SQLITE_INCLUDE_DIR sqlite3.h)
  if(TINYLSM_SQLITE_LIBRARY AND TINYLSM_SQLITE_INCLUDE_DIR)
    add_executable(tinylsm_rigorous_sqlite bench/rigorous_sqlite.cpp)
    target_include_directories(tinylsm_rigorous_sqlite PRIVATE ${TINYLSM_SQLITE_INCLUDE_DIR})
    target_link_libraries(tinylsm_rigorous_sqlite PRIVATE ${TINYLSM_SQLITE_LIBRARY} Threads::Threads)
    target_compile_options(tinylsm_rigorous_sqlite PRIVATE -Wall -Wextra)
  endif()
endif()
# YCSB-style skewed workloads (no external dependencies): Zipfian point
# mixes A/B/C/D/F plus short-scan E against tinylsm.
add_executable(tinylsm_ycsb bench/ycsb.cpp)
target_link_libraries(tinylsm_ycsb PRIVATE tinylsm)
target_compile_options(tinylsm_ycsb PRIVATE -Wall -Wextra)

option(TINYLSM_FUZZ "Build libFuzzer parsers (Clang required)" OFF)
if(TINYLSM_FUZZ)
  if(NOT CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    message(FATAL_ERROR "libFuzzer requires Clang")
  endif()
  foreach(parser wal sst)
    add_executable(fuzz_${parser} tests/fuzz/${parser}.cpp src/table.cpp)
    target_include_directories(fuzz_${parser} PRIVATE src include)
    target_compile_options(fuzz_${parser} PRIVATE -fsanitize=fuzzer,address,undefined)
    target_link_options(fuzz_${parser} PRIVATE -fsanitize=fuzzer,address,undefined)
    target_link_libraries(fuzz_${parser} PRIVATE Threads::Threads)
  endforeach()
endif()
