add_executable(tinylsm_cli app/main.cpp)
target_link_libraries(tinylsm_cli PRIVATE tinylsm)
add_executable(tinylsm_bench bench/main.cpp)
target_link_libraries(tinylsm_bench PRIVATE tinylsm)
add_executable(tinylsm_crash_acceptance tests/crash_acceptance.cpp)
target_link_libraries(tinylsm_crash_acceptance PRIVATE tinylsm)
add_test(NAME tinylsm_crash_acceptance COMMAND tinylsm_crash_acceptance)
set_tests_properties(tinylsm_crash_acceptance PROPERTIES TIMEOUT 60)
# Optional comparison benchmark: measures LevelDB with the identical workload so
# the portfolio charts plot a real head-to-head run (design section 7).
# Configure with -DTINYLSM_LEVELDB_INCLUDE_DIR=<dir> -DTINYLSM_LEVELDB_LIBRARY=<libleveldb.a>
set(TINYLSM_LEVELDB_INCLUDE_DIR "" CACHE PATH "LevelDB include directory (leveldb/db.h)")
set(TINYLSM_LEVELDB_LIBRARY "" CACHE FILEPATH "Path to libleveldb.a")
find_package(Snappy QUIET)
if(TINYLSM_LEVELDB_INCLUDE_DIR AND TINYLSM_LEVELDB_LIBRARY)
  add_executable(tinylsm_bench_leveldb bench/compare_leveldb.cpp)
  target_include_directories(tinylsm_bench_leveldb PRIVATE ${TINYLSM_LEVELDB_INCLUDE_DIR})
  target_link_libraries(tinylsm_bench_leveldb PRIVATE ${TINYLSM_LEVELDB_LIBRARY} Threads::Threads)
  if(TARGET Snappy::snappy)
    target_link_libraries(tinylsm_bench_leveldb PRIVATE Snappy::snappy)
  elseif(Snappy_FOUND)
    target_link_libraries(tinylsm_bench_leveldb PRIVATE ${SNAPPY_LIBRARIES})
  else()
    target_link_libraries(tinylsm_bench_leveldb PRIVATE snappy)
  endif()
  target_compile_options(tinylsm_bench_leveldb PRIVATE -Wall -Wextra)
endif()

option(TINYLSM_FUZZ "Build libFuzzer parsers (Clang required)" OFF)
if(TINYLSM_FUZZ)
  if(NOT CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    message(FATAL_ERROR "libFuzzer requires Clang")
  endif()
  foreach(parser wal sst)
    add_executable(fuzz_${parser} tests/fuzz/${parser}.cpp src/table.cpp)
    target_include_directories(fuzz_${parser} PRIVATE src include)
    target_compile_options(fuzz_${parser} PRIVATE -fsanitize=fuzzer,address,undefined)
    target_link_options(fuzz_${parser} PRIVATE -fsanitize=fuzzer,address,undefined)
    target_link_libraries(fuzz_${parser} PRIVATE Threads::Threads)
  endforeach()
endif()
